[package]
name = "traitenum"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bincode = "1.3.3"
proc-macro2 = "1"
quote = "1"
serde = { version = "1.0.190", features = ["derive"] }
syn = "2"

